- src/font.rs
- src/font_collection.rs
- src/font_descriptor.rs
For https://github.com/servo/servo/pull/4554.
> Upgrade to latest Rust.

- .travis.yml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/core-text-rs/41)
> Add Travis notfications for Homu

- src/font.rs
r? @metajack (or whoever)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/core-text-rs/40)
> Add a `Clone` impl to `CTFont`

- Cargo.toml
- src/font.rs
r? @metajack
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/core-text-rs/43)
> Add support for drawing glyphs and fetching their bounding rects

- Cargo.toml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/core-text-rs/44)
> Use more explicit dependency versions

- src/font.rs
- src/font_collection.rs
- src/font_descriptor.rs
These are all the structs as far as I can see.
Note that this is entirely untested... Let's see whether I got it right :-)
(Needed for https://github.com/servo/servo/pull/8908 )
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/core-text-rs/45)
> Derive Debug for CTFont, CTFontCollection, CTFontDescriptor

- Cargo.toml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/core-text-rs/47)
> Update the version number.

- Cargo.toml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/core-text-rs/48)
> Add some metadata.

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/core-text-rs/51)
> Update core-graphics to 0.4

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/core-text-rs/52)
> Test on stable.

- src/font_descriptor.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/core-text-rs/53)
> Add kCTFontColorGlyphsTrait

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/core-text-rs/54)
> Update to use core-graphics 0.5

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/core-text-rs/55)
> Update core-graphics and core-foundation dependencies

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/core-text-rs/56)
> Update core-graphics to 0.7

- Cargo.toml
API change, so did a major version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/core-text-rs/59)
> Two version changes

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/core-text-rs/66)
> Bump version for private/public nightly error change.

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/core-text-rs/69)
> Revert previous dependency upgrades.

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/core-text-rs/70)
> Update dependencies and bump major version.

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/core-text-rs/74)
> Update core-graphics to 0.12.1

- src/font.rs
- src/font_collection.rs
We should merge this before publishing a new version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/core-text-rs/77)
> Typed cfarray

- src/font.rs
- src/font_collection.rs
- src/font_descriptor.rs
- src/lib.rs
This cleans up the code a lot and gives an implementation of Clone.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/core-text-rs/79)
> Use macros from core-foundation for declaring types

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/core-text-rs/80)
> Bump the version for a new release
